import { createRoot } from 'react-dom/client';
import { HashRouter } from 'react-router-dom';
import './src/index.css';
import { ToastProvider } from './src/components/toast.jsx';
import Layout from './src/components/Layout.jsx';
import { Routes, Route } from 'react-router-dom';
import Fleet from './src/pages/Fleet.jsx';
import * as store from './src/core/store.js';
import { applyPrefs } from './src/state/prefs.js';

const iso = (m) => new Date(Date.now() - m * 60000).toISOString();
await store.openStore('u-owner');
applyPrefs();
let seq = 0; const put = (t, o) => store.save(t, { id: `00000000-0000-4000-8000-${String(++seq).padStart(12, '0')}`, ...o }, { fromServer: true });
const L = (user, o) => put('loads', { user_id: user, created_by: 'u-owner', currency: 'JMD', items: [], notes: '', rate_cents: 9500000, created_at: iso(300), ...o });
await L('u-marcus', { customer: 'Caribbean Cement', reference: 'KGN-2041', pickup_label: 'Rockfort, Kingston', drop_label: 'Montego Bay', status: 'in_transit', drop_at: iso(-180), pickup_at: iso(240) });
await L('u-andrea', { customer: 'Wisynco', reference: 'KGN-2042', pickup_label: 'Spanish Town', drop_label: 'Ocho Rios', status: 'booked', pickup_at: iso(-90), drop_at: iso(-300) });
await L('u-sasha', { customer: 'Seprod', reference: 'KGN-2030', pickup_label: 'Clarendon', drop_label: 'Kingston', status: 'delivered', drop_at: iso(60 * 30), pickup_at: iso(60 * 34) });
await L('u-marcus', { customer: 'GraceKennedy', reference: 'KGN-2039', pickup_label: 'Kingston', drop_label: 'Mandeville', status: 'delivered', drop_at: iso(60 * 50), pickup_at: iso(60 * 55) });
const M = (user, name, body, mins) => put('messages', { crew_id: 'c1', user_id: user, author_name: name, body, created_at: iso(mins), updated_at: iso(mins) });
await M('u-marcus', 'Marcus Reid', 'Morning boss. Loaded at Rockfort, heading out now.', 60 * 26);
await M('u-owner', 'Devon Brown', 'Good. Watch the Bog Walk gorge, they said flooding last night.', 60 * 26 - 3);
await M('u-marcus', 'Marcus Reid', 'Will do.', 60 * 26 - 4);
await M('u-andrea', 'Andrea Campbell', 'Can I take the Ocho Rios run after lunch?', 60 * 5);
await M('u-owner', 'Devon Brown', 'Yes. Customer wants it by 4.', 60 * 5 - 2);
await M('u-andrea', 'Andrea Campbell', 'On my way to the depot to pick up the paperwork. Will confirm when I am rolling.', 40);
await M('u-marcus', 'Marcus Reid', 'Bog Walk is flooded on the left lane. Use the old road.', 12);
await M('u-sasha', 'Sasha Grant', 'Thanks Marcus, telling Andrea now.', 5);
const A = (user, name, kind, note, mins, lat, lng) => put('road_alerts', { crew_id: 'c1', user_id: user, author_name: name, kind, note, lat, lng, created_at: iso(mins), expires_at: iso(-(360 - mins)), cleared_at: null });
await A('u-marcus', 'Marcus Reid', 'flood', 'Left lane under water near Bog Walk gorge', 12, 18.1, -77.0);
await A('u-andrea', 'Andrea Campbell', 'police', 'Checkpoint at Spanish Town roundabout', 95, 17.99, -76.95);
await A('u-sasha', 'Sasha Grant', 'roadworks', '', 200, 18.2, -77.3);
await put('settlements', { crew_id: 'c1', user_id: 'u-owner', driver_id: 'u-marcus', period_from: '2026-09-28', period_to: '2026-10-04', gross_cents: 28500000, deductions: [{ label: 'Cash advance', cents: 3000000 }, { label: 'Fuel card', cents: 1250000 }], net_cents: 24250000, currency: 'JMD', notes: 'Paid by bank transfer.', status: 'final', paid_at: null });
await put('settlements', { crew_id: 'c1', user_id: 'u-owner', driver_id: 'u-andrea', period_from: '2026-09-21', period_to: '2026-09-27', gross_cents: 19800000, deductions: [], net_cents: 19800000, currency: 'JMD', notes: '', status: 'paid', paid_at: iso(60 * 24 * 8) });
createRoot(document.getElementById('root')).render(<HashRouter><ToastProvider><Routes><Route element={<Layout />}><Route path="fleet/*" element={<Fleet />} /></Route></Routes></ToastProvider></HashRouter>);
