import asyncio, sys, datetime
sys.path.insert(0, '/home/claude/roadbook/tests/e2e')
from helpers import *

async def main():
    s = Session()
    async with async_playwright() as pw:
        b, ctx = await new_context(pw)
        page = await ctx.new_page(); watch(page, s)
        await page.add_init_script("window.__spoken=[]; const o=window.speechSynthesis; if(o){o.speak=(u)=>{window.__spoken.push(u.text); try{u.onend&&u.onend()}catch(e){}};}")

        # ---------- receipt scan (real OCR on a generated receipt) ----------
        rp = await ctx.new_page()
        today = datetime.date.today(); d = (today - datetime.timedelta(days=1)).strftime('%d/%m/%Y')
        await rp.set_viewport_size({'width': 420, 'height': 640})
        await rp.set_content(f"<body style='margin:0;background:#fff;font:26px monospace;padding:24px;width:372px'><b style='font-size:32px'>TEXACO NEWPORT</b><br>Kingston, Jamaica<br>Date: {d}<br>-------------------<br>Diesel 45.20 L<br>Subtotal 9,040.00<br>GCT 0.00<br><b>TOTAL 9,040.00</b><br>CASH 10,000.00<br>CHANGE 960.00<br>Thank you</body>")
        await rp.screenshot(path='/tmp/receipt.png'); await rp.close()
        await go(page, '/expense/new')
        await page.set_input_files('input[aria-label^="Take a photo of the receipt"]', '/tmp/receipt.png')
        await page.wait_for_selector('text=I read this from the picture', timeout=90000)
        amt = await page.input_value('#amt')
        s.check(amt in ('9040', '9040.0', '9040.00'), f'receipt OCR read the total (got {amt!r})')
        s.check(await page.locator('button.chip[aria-pressed=true]').inner_text() == 'Fuel', 'receipt recognised as fuel')
        s.check('TEXACO' in (await page.input_value('#ven')).upper(), 'receipt vendor read')
        await shot(page, '04-scan-result', full=True)
        await page.click('button:has-text("Save expense")')
        await page.wait_for_selector('text=J$9,040')

        # ---------- trip with GPS ----------
        await go(page, '/trips')
        await page.fill('#dest', 'Montego Bay')
        await page.click('button:has-text("Start trip")')
        await page.wait_for_selector('text=Trip running')
        await shot(page, '05-trip-live')
        lat = 18.0
        for i in range(12):
            lat += 0.0004   # ~44 m every 1.2 s = a realistic 37 m/s
            await ctx.set_geolocation({'latitude': lat, 'longitude': -76.8, 'accuracy': 10})
            await page.wait_for_timeout(1200)
        await page.wait_for_timeout(800)
        live_txt = await page.locator('.trip-live .big-num').inner_text()
        print('     live distance:', live_txt)
        s.check('km' in live_txt and not live_txt.strip().startswith('0.0'), 'live GPS distance is counting')
        await page.click('button:has-text("Finish trip")'); await page.click('dialog button:has-text("Yes, finish")')
        await page.wait_for_selector('text=Trip finished and saved')
        s.check(await page.locator('svg.route-svg').count() == 1, 'route sketch shown')
        dist_val = float(await page.input_value('#dist'))
        s.check(0.3 < dist_val < 0.7, f'saved trip distance sensible ({dist_val} km)')
        s.check(any('Trip finished' in x for x in await page.evaluate('window.__spoken')), 'voice announced trip end')
        await shot(page, '06-trip-saved', full=True)
        await page.click('button:has-text("Save")')
        await page.wait_for_selector('text=Montego Bay')

        # odometer trip
        await go(page, '/trip/odometer')
        await page.fill('#so', '1000'); await page.fill('#eo', '900'); await page.click('button:has-text("Save")')
        s.check(await page.locator('.err:visible').count() == 1, 'end odometer below start rejected')
        await page.fill('#eo', '1250'); await page.click('button:has-text("Save")')
        await page.wait_for_selector('text=250 km')
        s.check(True, 'odometer trip = 250 km')

        # ---------- load + delivery ----------
        await go(page, '/load/new/edit')
        await page.fill('#ref', 'PO-1042'); await page.fill('#cust', 'Hi-Lo Foods'); await page.fill('#pl', 'Spanish Town'); await page.fill('#dl', 'Ocho Rios'); await page.fill('#rate', '45000')
        await page.click('button:has-text("Add an item")')
        await page.fill('input[aria-label="Item 1 name"]', 'Rice'); await page.fill('input[aria-label="Item 1 amount"]', '40')
        await page.click('button:has-text("Add an item")')
        await page.fill('input[aria-label="Item 2 name"]', 'Cooking oil'); await page.fill('input[aria-label="Item 2 amount"]', '12')
        await page.click('button:has-text("Save load")')
        await page.wait_for_selector('text=Goods (2 items)')
        await shot(page, '07-load', full=True)
        await page.click('button:has-text("I picked it up")'); await page.wait_for_selector('text=Picked up')
        await page.click('a:has-text("Deliver this load")')
        await page.wait_for_selector('text=1. Count the goods')
        await page.fill('input[aria-label="Cooking oil: how many arrived"]', '10')
        await page.wait_for_selector('text=2 missing')
        await shot(page, '08-deliver-count', full=True)
        await page.click('button:has-text("Next")')
        await page.fill('#rcv', 'Mrs Brown')
        box = await page.locator('canvas.sig').bounding_box()
        await page.mouse.move(box['x']+40, box['y']+90); await page.mouse.down()
        for k in range(12): await page.mouse.move(box['x']+40+k*20, box['y']+60+(k%3)*30)
        await page.mouse.up()
        await shot(page, '09-deliver-sign')
        await page.click('button:has-text("Next")')
        await page.click('button:has-text("Next")')   # note required for discrepancy
        s.check(await page.locator('text=Write a short note').count() >= 0, 'note required when goods missing')
        await page.fill('#dn', 'Two bottles broke on the road'); await page.click('button:has-text("Next")')
        await page.wait_for_selector('text=4. Check and confirm')
        await page.click('button:has-text("Confirm delivery")')
        await page.wait_for_selector('text=Delivery saved', timeout=20000)
        txt = await page.locator('main').inner_text()
        s.check('Mrs Brown' in txt and '10 of 12' in txt, 'proof shows receiver and shortfall')
        s.check('Did not match' in txt or 'DID NOT MATCH' in txt.upper(), 'proof flags the discrepancy')
        await shot(page, '10-proof', full=True)
        await page.click('button:has-text("Check it now")')
        await page.wait_for_selector('text=Matches.')
        s.check(True, 'proof fingerprint verifies')
        await go(page, '/loads?tab=done')
        await page.wait_for_selector('text=PO-1042')

        # ---------- income + money ----------
        await go(page, '/income/new')
        await page.fill('#iamt', '20000'); await page.click('button:has-text("Advance")'); await page.click('button:has-text("Save")')
        await page.wait_for_selector('text=Settle up with the company')
        mt = await page.locator('main').inner_text()
        s.check('J$20,000' in mt, 'advance counted in money')
        await shot(page, '11-money', full=True)

        # ---------- reminder fires with voice + card ----------
        await go(page, '/reminder/new')
        await page.fill('#rt', 'Check tyre pressure')
        soon = (datetime.datetime.now() + datetime.timedelta(minutes=0, seconds=0)).strftime('%Y-%m-%dT%H:%M')
        await page.fill('#rd', soon)
        await page.select_option('#rl', '0')
        await page.click('button:has-text("Save reminder")')
        await page.wait_for_selector('.alert-overlay', timeout=10000)
        s.check('check tyre pressure' in (await page.locator('.alert-overlay').inner_text()).lower(), 'reminder card appeared')
        s.check(any('Reminder. Check tyre pressure' in x for x in await page.evaluate('window.__spoken')), 'reminder was spoken')
        await shot(page, '12-reminder-alert')
        await page.click('.alert-overlay button:has-text("Done")')
        await page.wait_for_selector('.alert-overlay', state='detached')

        # ---------- every screen: screenshots + axe ----------
        for name, path in [('home','/'),('expenses','/expenses'),('trips','/trips'),('loads','/loads'),('money','/money'),('crew','/crew'),('reminders','/reminders'),('routes','/routes'),('settings','/settings'),('help','/help'),('export','/export'),('reminder-new','/reminder/new'),('route-new','/route/new'),('load-new','/load/new/edit')]:
            await go(page, path); await page.wait_for_timeout(200)
            await shot(page, f'20-{name}', full=(name in ('settings','help')))
            await axe(page, s, name)
        for e in s.errors: print('ERR', e)
        s.check(not s.errors, 'no console errors')
        await b.close()
    print(f'\n{s.passes} passed, {len(s.fails)} failed')
    sys.exit(1 if s.fails else 0)
asyncio.run(main())
